// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// ENV_FILE выбирает файл переменных (по умолчанию .env) — тем же ключом, что и
// приложение (src/config/load-env.ts). Нужно, чтобы миграции можно было накатить
// на демо-БД: ENV_FILE=.env.demo npx prisma migrate deploy.
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config({ path: process.env["ENV_FILE"]?.trim() || ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
